This is the inital import from my private repo to the public one.
git-svn-id: https://judy.svn.sourceforge.net/svnroot/judy/tags/Judy-1.0.0@4 6390f24f-2af0-0310-aa40-fab754e6522e

diff --git a/test/Checkit b/test/Checkit
--- a/test/Checkit
+++ b/test/Checkit
@@ -1,56 +1,63 @@
 #!/bin/sh
-# @(#) $Revision: 4.5 $ $Source: /judy/test/manual/Checkit $
+CC=${CC:-cc}
+
 echo
 echo "=== +++++++++ This test runs in 15 seconds on a PIII 750Mhz +++++++"
 
 LIBJUDY=`find ../ -name libJudy.a`
-#LIBJUDY='../../src/JudyCommon/libJudy.a'
 JUDY_H=`find ../ -name Judy.h`
-INCLUDE=-I../src/
 
-cc $INCLUDE -O SLcompare.c         -DHASHMETHOD     -o SL_Hash
-cc $INCLUDE -O SLcompare.c         -DSPLAYMETHOD    -o SL_Splay
-cc $INCLUDE -O SLcompare.c         -DREDBLACKMETHOD -o SL_Redblack
+echo "$CC -O SLcompare.c -DHASHMETHOD -o SL_Hash"
+      $CC -O SLcompare.c -DHASHMETHOD -o SL_Hash
+
+echo "$CC -O SLcompare.c -DSPLAYMETHOD -o SL_Splay"
+      $CC -O SLcompare.c -DSPLAYMETHOD -o SL_Splay
+
+echo "$CC -O SLcompare.c -DREDBLACKMETHOD -o SL_Redblack"
+      $CC -O SLcompare.c -DREDBLACKMETHOD -o SL_Redblack
+
+
 echo
 echo Compiling with Judy library: $LIBJUDY
 echo
-cc $INCLUDE -O SLcompare.c -DJUDYMETHOD -o SL_Judy     $LIBJUDY -lm
+echo "$CC -O -I../src SLcompare.c -DJUDYMETHOD -o SL_Judy $LIBJUDY -lm"
+      $CC -O -I../src SLcompare.c -DJUDYMETHOD -o SL_Judy $LIBJUDY -lm
 if [ $? -ne 0 ] ; then
-echo "===  Failed: cc SLcompare.c -DJUDYMETHOD"
+echo "===  $? Failed: $CC SLcompare.c -DJUDYMETHOD"
 exit $?
 fi
-cc $INCLUDE -O Judy1LCheck.c            -o Judy1LCheck $LIBJUDY -lm
+echo "$CC -O -I../src Judy1LHCheck.c -o Judy1LHCheck $LIBJUDY -lm"
+      $CC -O -I../src Judy1LHCheck.c -o Judy1LHCheck $LIBJUDY -lm
 if [ $? -ne 0 ] ; then
-echo "===  Failed: cc Judy1LCheck.c"
+echo "===  $? Failed: $CC Judy1LHCheck.c"
 exit $?
 fi
-cc $INCLUDE -O Judy1LTime.c -DNOINLINE  -o Judy1LTime  $LIBJUDY -lm
+echo "$CC -O -I../src Judy1LHTime.c -DNOINLINE  -o Judy1LHTime  $LIBJUDY -lm"
+      $CC -O -I../src Judy1LHTime.c -DNOINLINE  -o Judy1LHTime  $LIBJUDY -lm
 if [ $? -ne 0 ] ; then
-echo "===  Failed: cc Judy1LTime.c"
+echo "===  $? Failed: $CC Judy1LHTime.c"
 exit $?
 fi
-
 
 #  -OR-    if Judy is installed, these can be compiled from anywhere:
-
-
-#cc -O SLcompare.c -DJUDYMETHOD     -o SL_Judy     -lJudy -lm 
-#cc -O Judy1LCheck.c                -o Judy1LCheck -lJudy -lm
-#cc -O Judy1LTime.c -DNOINLINE      -o Judy1LTime  -lJudy -lm
-
+#cc -O SLcompare.c -DJUDYMETHOD      -o SL_Judy      -lJudy -lm 
+#cc -O Judy1LHCheck.c                -o Judy1LHCheck -lJudy -lm
+#cc -O Judy1LHTime.c                 -o Judy1LHTime  -lJudy -lm
 echo "===  Pass: Compile of tests"
+
 echo
-echo "     Validate Judy1/JudyL functions (except Judy*ByCount)"
-./Judy1LCheck -n 300000 -B20 > /dev/null
+echo "     Validate Judy1/JudyL/JudyHS functions (except Judy*ByCount)"
+./Judy1LHCheck -n 300000 -B20 > /dev/null
 if [ $? -ne 0 ] ; then
-echo "===  Failed: Judy1/JudyL validate program"
+echo "===  $? Failed: Judy1/JudyL/JudyHS validate program"
 exit $?
 fi
-echo "===  Pass: Judy1/JudyL validate program"
-echo
-echo "     Do a few timings tests of Judy1/JudyL"
-echo
+echo "===  Pass: Judy1/JudyL/JudyHS validate program"
 
+
+echo
+echo "     Do a few timings tests of Judy1/JudyL/JudyHS"
+echo
 # Pop1    is: current number of Indexes stored in Judy array
 # Measmts is: lookups to make measurement
 # J1      is: Judy1
@@ -58,14 +65,15 @@ echo
 # /I      is: per Index
 # MU      is: Memory Used (allocated thru malloc(3))
 # HEAP    is: Memory change measured with sbrk(0)
-
 echo "      Pop1   Measmts    J1S    JLI    J1T    JLG J1MU/I JLMU/I HEAP/I"
-./Judy1LTime  -n 2000000 -P1 -B19 | grep -v "^#"
-echo "===  Pass: Judy1/JudyL performance program"
+./Judy1LHTime  -n 2000000 -P1 -B19 | grep -v "^#"
+echo "===  Pass: Judy1/JudyL/JudyHS performance program"
+
+
+
 echo
 echo "     Do a few timings tests of JudySL and friends"
 echo
-
 # lines         is: number of lines in source file
 # avg_linelen   is: average bytes per line
 # getline       is: average time go get a line and remove white space
@@ -74,14 +82,13 @@ echo
 # store/ln      is: average insert time (including duplicates)
 # lookup/ln     is: average lookup time in same order as inserts
 # ADT           is: Abstract Data Type method
-
 echo "   lines avg_linelen  getline   StoreD RAMused/line  store/ln lookup/ln ADT"
-./SL_Hash     /etc/passwd | grep HASH
-./SL_Splay    /etc/passwd | grep SPLAY
-./SL_Redblack /etc/passwd | grep REDBLACK
-./SL_Judy     /etc/passwd | grep JUDY
+./SL_Hash     ../Makefile | grep HASH
+./SL_Splay    ../Makefile | grep SPLAY
+./SL_Redblack ../Makefile | grep REDBLACK
+./SL_Judy     ../Makefile | grep JUDY
 if [ $? -ne 0 ] ; then
-echo "===  Failed: JudySL if StoreD numbers are all the same" 
+echo "===  $? Failed: JudySL if StoreD numbers are all the same" 
 exit $?
 fi
 echo "===  Pass: JudySL if StoreD numbers are all the same"
